### ISSUE TITLE
Changing the App Title

### ISSUE THREAD

**Issue by dhwaj1902** [codeforcauseorg/edu-client#188]
Change the App Title from 'React App' to 'Edu Client'.
![image](https://user-images.githubusercontent.com/57860123/113340894-18ed4d00-934a-11eb-861c-075cac28969a.png)

**Comment by dhwaj1902** [comment]
By mistake I have made pull request in another issue, This is the pr for this issue [Pr](https://github.com/codeforcauseorg/edu-client/pull/187/commits/4f58500372f28da46228f9aff1b364997e00711b)

**Comment by Abhijay007** [comment]
@dhwaj1902 we may don't need it right now as our main focus is the android app that's why we not even replace our favicon for now but if you really wanna change it try to make changes in your existing PR as i think to open a separate pr for this may not that fuitlful. 

PS: I am not a maintainer you might need approval for this form @Abhishek-kumar09

**Comment by dhwaj1902** [comment]
@Abhishek-kumar09 can close this issue because I already pushed my changes to this [commit](https://github.com/codeforcauseorg/edu-client/pull/198/commits/4f58500372f28da46228f9aff1b364997e00711b)

**Comment by karankv26** [comment]
@Abhishek-kumar09 done bro...

**Comment by dhwaj1902** [comment]
@karankv26 bro I have already pushed the changes and the pr is already merged. I asked @Abhishek-kumar09 to close this issue.

**Comment by karankv26** [comment]
Ohh okay...fine...

**Comment by rizwan2000rm** [comment]
@dhwaj1902 You can close it yourself as you are the author of this issue.
