### ISSUE TITLE
Add: about us page

### ISSUE THREAD

**Issue by rajatgupta24** [codeforcauseorg/edu-client#48]
Hi @KeenWarrior @kunal-kushwaha ,
We should add:

- About us page
- Terms & condition
- Privacy policy

Can I work on them.

**Comment by himanshu211raj** [comment]
@kunal-kushwaha @KeenWarrior @Abhishek-kumar09 can i work on this issue?

**Comment by nitinosiris** [comment]
I would like to work on this issue too!

**Comment by Abhishek-kumar09** [comment]
Start with creating a docs layout, just like we have MainLayout. You can learn more about this from here: https://github.com/codeforcauseorg/codeforcause.org/tree/development/src/layouts

You all can work on this issue together by delegating tasks, or @rajatgupta24 can also work alone since he created it and asked for assignment.
