### ISSUE TITLE
confusion

### ISSUE THREAD

**Issue by san0808** [codeforcauseorg/edu-client#87]
![image](https://user-images.githubusercontent.com/72181610/111065183-68c0bd00-84de-11eb-8586-fbdc1e86505a.png)
I thought the main idea of project was to create a platform where one can take live classes ,take tests ,upload notes and bea education system between a teacher and the student 
but the pic shows something else 
please just tell me the idea i thought of was wrong or the code was meant to be improved later

**Comment by Abhishek-kumar09** [comment]
Sorry @san0808 but it seems like you have opened a different project.

It is not edu-client and trust me edu-client goals is to empower education and learning culture for the development of society.

Please let me know if you have any other confusion.

Please follow the issue-template while creating an issue so that we could be provided with more knowledge of the real matter.

**Comment by san0808** [comment]
![image](https://user-images.githubusercontent.com/72181610/111065739-40868d80-84e1-11eb-8b7e-c812311c81ac.png)
is this not the project (sorry if i am rude in any way i am pretty new in using node.js i tried using this in development mode with the help of readme and google search)
![image](https://user-images.githubusercontent.com/72181610/111065807-a246f780-84e1-11eb-9622-54318719fb2b.png)
I used npm start for the development mode
please tell me if i am wrong

**Comment by Abhishek-kumar09** [comment]
> is this not the project (sorry if i am rude in any way i am pretty new in using node.js i tried using this in development mode with the help of readme and google search)

Not at all, thanks for raising your doubt btw. 

You are running an old project version. Maybe you have cloned the repo in the very initial phase of development. 

So we had took some part of the appbar from the codeforcause website for testing and running signIn feature and that's why you can see the appbar with headers. 

Please rebase your project to latest main branch, it has all the latest changes.

**Comment by san0808** [comment]
ok thanks bro

**Comment by Abhishek-kumar09** [comment]
Okay, cool. I am closing this issue.
